name: GCMSFormer
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
dependencies:
  - alabaster=0.7.12=py_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py37hcc03f2d_2
  - arrow=1.2.2=pyhd8ed1ab_0
  - astroid=2.5.8=py37h03978a9_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - autopep8=1.6.0=pyhd8ed1ab_1
  - babel=2.10.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bcrypt=3.2.2=py37hcc03f2d_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=22.3.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=5.0.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37hcc03f2d_1004
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.0=py37hd8e9650_0
  - chardet=4.0.0=py37h03978a9_3
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.1.3=py37h03978a9_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cookiecutter=1.7.3=pyh6c4a22f_1
  - cryptography=37.0.1=py37h21b164f_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.6.0=py37hf2a7229_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20200713=pyh9f0ad1d_0
  - docutils=0.16=py37h03978a9_3
  - entrypoints=0.4=pyhd8ed1ab_0
  - flake8=4.0.1=pyhd8ed1ab_2
  - flit-core=3.8.0=pyhd8ed1ab_0
  - freetype=2.10.4=h546665d_1
  - gettext=0.19.8.1=ha2e2712_1008
  - gst-plugins-base=1.20.2=he07aa86_1
  - gstreamer=1.20.2=hdff456e_1
  - icu=70.1=h0e60522_0
  - idna=3.3=pyhd8ed1ab_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.2.0=py37h03978a9_0
  - importlib_metadata=1.5.0=py37_0
  - importlib_resources=5.7.1=pyhd8ed1ab_1
  - inflection=0.5.1=pyh9f0ad1d_0
  - intel-openmp=2022.1.0=h57928b3_3787
  - intervaltree=3.0.2=py_0
  - ipykernel=6.13.1=py37h90c5f73_0
  - ipython=7.33.0=py37h03978a9_0
  - ipython_genutils=0.2.0=py_1
  - isort=5.10.1=pyhd8ed1ab_0
  - jedi=0.18.1=py37h03978a9_1
  - jellyfish=0.9.0=py37hcc03f2d_1
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - jpeg=9e=h8ffe710_1
  - jsonschema=4.6.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py37h03978a9_7
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_console=6.4.4=py37haa95532_0
  - jupyter_core=4.10.0=py37h03978a9_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - keyring=23.6.0=py37h03978a9_0
  - krb5=1.19.3=h1176d77_0
  - lazy-object-proxy=1.7.1=py37hcc03f2d_1
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=15_win64_mkl
  - libcblas=3.9.0=15_win64_mkl
  - libclang=14.0.5=default_h77d9078_0
  - libclang13=14.0.5=default_h77d9078_0
  - libdeflate=1.10=h8ffe710_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.70.2=h3be07f2_4
  - libiconv=1.16=he774522_0
  - liblapack=3.9.0=15_win64_mkl
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libtiff=4.3.0=hc4061b1_4
  - libuv=1.43.0=h8ffe710_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.2.12=h8ffe710_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py37hcc03f2d_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37hcc03f2d_1005
  - mkl=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - mypy_extensions=0.4.3=py37h03978a9_5
  - nbclient=0.6.4=pyhd8ed1ab_1
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - notebook=6.3.0=py37h03978a9_0
  - numpy=1.21.6=py37h2830a78_0
  - numpydoc=1.4.0=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1o=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=1.19.2.1=1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=2.11.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py37h8675073_0
  - pip=22.1.2=pyhd8ed1ab_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - pluggy=1.0.0=py37h03978a9_3
  - poyo=0.5.0=py_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - prompt_toolkit=3.0.36=hd8ed1ab_0
  - psutil=5.9.1=py37hcc03f2d_0
  - pthread-stubs=0.4=hcd874cb_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycodestyle=2.8.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.1.1=pyhd8ed1ab_0
  - pyflakes=2.4.0=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pylint=2.7.2=py37h03978a9_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py37ha54c9ec_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.4=py37h35e25fb_1
  - pyqt5-sip=12.9.0=py37hf2a7229_1
  - pyqtwebengine=5.15.4=py37h35e25fb_1
  - pyrsistent=0.18.1=py37hcc03f2d_1
  - pysocks=1.7.1=py37h03978a9_5
  - python=3.7.12=h7840368_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python-lsp-black=1.2.1=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.0.0=pyhd8ed1ab_0
  - python-lsp-server=1.4.1=pyhd8ed1ab_1
  - python-slugify=6.1.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=pyhd8ed1ab_0
  - pywin32=303=py37hcc03f2d_0
  - pywin32-ctypes=0.2.0=py37h03978a9_1005
  - pywinpty=2.0.2=py37h5da7b33_0
  - pyzmq=23.1.0=py37hcce574b_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.2.1=pyhd8ed1ab_0
  - qt-main=5.15.4=h467ea89_2
  - qt-webengine=5.15.4=h7325c83_3
  - qtawesome=1.1.1=pyhd8ed1ab_0
  - qtconsole=5.3.1=pyhd8ed1ab_0
  - qtconsole-base=5.3.1=pyha770c72_0
  - qtpy=2.1.0=pyhd8ed1ab_0
  - requests=2.28.0=pyhd8ed1ab_0
  - rope=1.1.1=pyhd8ed1ab_0
  - rtree=1.0.0=py37h13cc57e_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=62.3.4=py37h03978a9_0
  - sip=6.5.1=py37hf2a7229_2
  - six=1.16.0=pyh6c4a22f_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sphinx=3.5.4=pyh44b312d_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - spyder=5.3.1=py37h03978a9_0
  - spyder-kernels=2.3.1=py37h03978a9_0
  - sqlite=3.38.5=h8ffe710_0
  - tbb=2021.5.0=h2d74725_1
  - terminado=0.15.0=py37h03978a9_0
  - text-unidecode=1.3=py_0
  - textdistance=4.2.2=pyhd8ed1ab_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=0.11.0=py37_cu113
  - torchvision=0.12.0=py37_cu113
  - tornado=6.1=py37hcc03f2d_3
  - traitlets=5.2.2.post1=pyhd8ed1ab_0
  - typed-ast=1.4.3=py37h2bbff1b_1
  - typing-extensions=4.2.0=hd8ed1ab_1
  - typing_extensions=4.2.0=pyha770c72_1
  - ucrt=10.0.20348.0=h57928b3_0
  - ujson=5.3.0=py37hf2a7229_0
  - unidecode=1.3.4=pyhd8ed1ab_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - watchdog=2.1.9=py37h03978a9_0
  - wcwidth=0.2.5=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py37h03978a9_4
  - winpty=0.4.3=4
  - wrapt=1.11.2=py37h4ab8f01_1
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.5=h62dcd97_1
  - yaml=0.1.6=0
  - yapf=0.32.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h8ffe710_0
  - zstd=1.5.2=h6255e5f_1
  - pip:
    - absl-py==1.1.0
    - cycler==0.11.0
    - dill==0.3.5.1
    - etils==0.6.0
    - filelock==3.8.0
    - fonttools==4.37.1
    - googleapis-common-protos==1.56.2
    - huggingface-hub==0.9.1
    - ipywidgets==8.0.1
    - joblib==1.2.0
    - jupyterlab-widgets==3.0.2
    - kiwisolver==1.4.4
    - matplotlib==3.5.3
    - pandas==1.3.5
    - promise==2.3
    - protobuf==3.20.1
    - pyitcast==1.0.4
    - pyyaml==6.0
    - regex==2022.8.17
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.0
    - tensorflow-metadata==1.8.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - tqdm==4.64.0
    - transformers==4.21.2
    - wget==3.2
    - widgetsnbextension==4.0.2
prefix: D:\anaconda\envs\GCMSFormer
